### ISSUE TITLE
If key is bytes, encode works, decode fails

### ISSUE THREAD

**Issue by friedcell** [mpdavis/python-jose#126]
```>>> from jose import jwt
>>> key = b'key'
>>> token = jwt.encode({'key': 'value'}, key, algorithm='HS256')
>>> jwt.decode(token, key, algorithms=['HS256'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python3.5/site-packages/jose/jwt.py", line 134, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
  File "/lib/python3.5/site-packages/jose/jws.py", line 75, in verify
    _verify_signature(signing_input, header, signature, key, algorithms)
  File "/lib/python3.5/site-packages/jose/jws.py", line 260, in _verify_signature
    keys = _get_keys(key)
  File "/lib/python3.5/site-packages/jose/jws.py", line 227, in _get_keys
    if 'keys' in key:
TypeError: a bytes-like object is required, not 'str'
```

I think either both should work or both should fail.

**Comment by blag** [comment]
I think this is fixed in #139.

**Comment by SharkFourSix** [comment]
I'm still getting this error. How do I fix this please? I can encode but the error happens when decoding.

**Comment by bossjones** [comment]
Unfortunately i'm seeing the same thing. Here's my output from ipython ( Python 3.7.4 ) using release 3.1.0:

```
ipython
Python 3.7.4 (default, Sep  2 2019, 19:26:58)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from jose import jwt

In [2]: key = b'key'
   ...: token = jwt.encode({'key': 'value'}, key, algorithm='HS256')
   ...: jwt.decode(token, key, algorithms=['HS256'])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-beb09644f24d> in <module>
      1 key = b'key'
      2 token = jwt.encode({'key': 'value'}, key, algorithm='HS256')
----> 3 jwt.decode(token, key, algorithms=['HS256'])

~/.pyenv/versions/3.7.4/envs/ultron8_venv374_jupyter/lib/python3.7/site-packages/jose/jwt.py in decode(token, key, algorithms, options, audience, issuer, subject, access_token)
    152
    153     try:
--> 154         payload = jws.verify(token, key, algorithms, verify=verify_signature)
    155     except JWSError as e:
    156         raise JWTError(e)

~/.pyenv/versions/3.7.4/envs/ultron8_venv374_jupyter/lib/python3.7/site-packages/jose/jws.py in verify(token, key, algorithms, verify)
     78
     79     if verify:
---> 80         _verify_signature(signing_input, header, signature, key, algorithms)
     81
     82     return payload

~/.pyenv/versions/3.7.4/envs/ultron8_venv374_jupyter/lib/python3.7/site-packages/jose/jws.py in _verify_signature(signing_input, header, signature, key, algorithms)
    264         raise JWSError('The specified alg value is not allowed')
    265
--> 266     keys = _get_keys(key)
    267     try:
    268         if not _sig_matches_keys(keys, signing_input, signature, alg):

~/.pyenv/versions/3.7.4/envs/ultron8_venv374_jupyter/lib/python3.7/site-packages/jose/jws.py in _get_keys(key)
    231
    232     # JWK Set per RFC 7517
--> 233     if 'keys' in key:
    234         return key['keys']
    235

TypeError: a bytes-like object is required, not 'str'

In [3]: import jose

In [4]: jose.__version__
Out[4]: '3.1.0'

In [5]:
```
